# 生产环境配置
spring:
  # Elasticsearch 配置
  elasticsearch:
    uris: http://49.233.1.153:9200
    username: elastic
    password: 123456

# 日志配置
logging:
  level:
    '[com.spring.elastic]': info
  file:
    name: logs/spring-boot-elastic.log
    max-size: 10MB
    max-history: 30
