# 开发环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_labs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 

  # Elasticsearch 配置
  elasticsearch:
    uris: http://49.233.1.153:9200
    username: elastic
    password: 123456

# MongoDB 配置
mongo-plus:
  data:
    mongodb:
      host: 49.233.1.153
      port: 27017
      database: test
      username: admin
      password: 123456
      authentication-database: admin
  configuration:
    logic:
      open: true
      auto-fill: true
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-data-type: Integer

# 日志配置
logging:
  level:
    '[com.spring.elastic]': debug
