# 开发环境配置
spring:
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password: 

  # Elasticsearch 配置
  elasticsearch:
    uris: http://49.233.1.153:9200
    username: elastic
    password: 123456

# 日志配置
logging:
  level:
    '[com.spring.es]': debug
