# 生产环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# 日志配置
logging:
  level:
    '[com.github.jeremy]': info
  file:
    name: logs/spring-redis-string-demo.log
    max-size: 10MB
    max-history: 30
