# 生产环境配置
spring:
  # Redis 配置
  redis:
    host: 49.233.1.153
    port: 6379
    password: YourStrongPassword123

# MongoDB 配置
mongo-plus:
  data:
    mongodb:
      host: 49.233.1.153
      port: 27017
      database: test
      username: admin
      password: 123456
  configuration:
    logic:
      open: true
      auto-fill: true
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-data-type: Integer

# 日志配置
logging:
  level:
    '[com.spring.mongo]': info
  file:
    name: logs/spring-boot-mongo.log
    max-size: 10MB
    max-history: 30
