# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /mongo

# 应用基本配置
spring:
  application:
    name: spring-mongo-demo

  # 环境配置
  profiles:
    active: dev

# 日志配置
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%logger{36}){cyan} %clr(:){faint} %m%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} %5p ${PID:- } --- [%thread] %logger{36} : %m%n'
